### ISSUE TITLE
all plugins: Gracefully quit the honeypot if ports are used

### ISSUE THREAD

**Issue by redragonx** [redragonx/SuperHoneyPot#71]
`15:38:13 ツ superX:(master)~/DataMain/srcode/SuperHoneyPot >sudo python2.7 honeypot/honey_loader/loader.py 
[sudo] password for root: 
Bind failure: [Errno 98] Address already in use
Connection failure: 'NoneType' object has no attribute 'listen'
Failure to complete connection: 'NoneType' object is not iterable
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in **bootstrap_inner
    self.run()
  File "/home/stephen/DataMain/srcode/SuperHoneyPot/honeypot/plugins/ssh_plugin.py", line 131, in run
    self.display_output()
  File "/home/stephen/DataMain/srcode/SuperHoneyPot/honeypot/plugins/ssh_plugin.py", line 205, in display_output
    print('SSH Attack: ' + server_plugin.time.__str**() + ' from ' + server_plugin.clientIP + ' on port ' + server_plugin.PORT.**str**() + '.')
TypeError: cannot concatenate 'str' and 'NoneType' objects

`

**Comment by WDKing** [comment]
Investigating issue, since it is tied with #52 which is closed, but this is not.

**Comment by WDKing** [comment]
Added catch for socket errors to add additional capability for failure, since issue with closing ports with ctrl-c apparently already resolved.
