### ISSUE TITLE
found bug in telnet plugin

### ISSUE THREAD

**Issue by redragonx** [redragonx/SuperHoneyPot#80]
Given the input

```
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.


Login authentication


Username: ytyy
password: uytyty
>> exit
Invalid command
>> ^\
}


Connection closed by foreign host.
```

will show this error

```

Connected with 127.0.0.1:36670
127.0.0.1:36670: Connection terminated.
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/stephen/DataMain/srcode/SuperHoneyPot/honeypot/plugins/telnet_reader.py", line 185, in run
    self.send_output()
  File "/home/stephen/DataMain/srcode/SuperHoneyPot/honeypot/plugins/telnet_reader.py", line 193, in send_output
    'Data':self.data}}})
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 8: invalid start byte
```

**Comment by mbatkali** [comment]
Working  on it

**Comment by mbatkali** [comment]
This is a per OS bug. In Unix, telnet will not use Binary mode by default. So change the telnetrc file, and add the line: default toggle outbinary

sudo nano ~/.telnetrc
default toggle outbinary

This will screw with other features within Unix, just an fyi.

**Comment by fred15** [comment]
Haven't actually looked at this, I think I can actually fix it just forgot about it

**Comment by redragonx** [comment]
Closing as Fred fixed it.
